---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetris
  namespace: tetris
spec:
  interval: 1m
  install:
    createNamespace: true
  releaseName: tetris
  chart:
    spec:
      chart: ./charts/tetris
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: from-docker-to-helm
        namespace: flux-system
      interval: 1m
  values:
    replicas: 5
